server:
  port: 7800
spring:
  application:
    name: learn-zipkin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false